/* This file is automatically generated. */
/* Editing is useless.                   */

void packed_to_int_list(int *list, const uint64_t *packed)
{
  list[ 0] = (int) (packed[0] >>  0) & 0x7;
  list[ 1] = (int) (packed[0] >>  3) & 0x7;
  list[ 2] = (int) (packed[0] >>  6) & 0x3f;
  list[ 3] = (int) (packed[0] >> 12) & 0x7;
  list[ 4] = (int) (packed[0] >> 15) & 0x7;
  list[ 5] = (int) (packed[0] >> 18) & 0x3f;
}

void int_list_to_packed(uint64_t *packed, const int *list)
{
  packed[0] = 0;
  packed[0] |= (((uint64_t) list[ 0]) <<  0);
  packed[0] |= (((uint64_t) list[ 1]) <<  3);
  packed[0] |= (((uint64_t) list[ 2]) <<  6);
  packed[0] |= (((uint64_t) list[ 3]) << 12);
  packed[0] |= (((uint64_t) list[ 4]) << 15);
  packed[0] |= (((uint64_t) list[ 5]) << 18);
}

void int_list2_to_packed(uint64_t *packed, const int *list0, const int *list1)
{
  packed[0] = 0;
  packed[0] |= (((uint64_t) list0[ 0]) <<  0);
  packed[0] |= (((uint64_t) list0[ 1]) <<  3);
  packed[0] |= (((uint64_t) list0[ 2]) <<  6);
  packed[0] |= (((uint64_t) list1[ 0]) << 12);
  packed[0] |= (((uint64_t) list1[ 1]) << 15);
  packed[0] |= (((uint64_t) list1[ 2]) << 18);
}

