/* This file is automatically generated. */
/* Editing is useless.                   */

#define CFG_CONN_TABLES                1
#define CFG_MP_STATES_FR               "rev"
#define CFG_FILENAME_TABLES_FR_H       "tables_rev.h"
#define CFG_FILENAME_TABLES_MISS_H     "tables_miss_n_tables.h"
#define CFG_FILENAME_CODE_FR_H         "code_rev.h"

#define CFG_NUM_MP_STATES              711
#define CFG_NUM_NLJ_STATES             10
#define CFG_NUM_SP_STATES              33
#define CFG_NUM_SP_STATES0             3
#define CFG_NUM_SP_STATES1             3
#define CFG_MAX_SUM_E                  4
#define CFG_MAX_J                      7
#define CFG_SUM_M                      2
#define CFG_PACK_WORDS                 1
#define CFG_HASH_MP_PAD64              0
#define CFG_2J_INITIAL                 2
#define CFG_2J_FINAL                   2
#define CFG_2T_INITIAL                 6
#define CFG_2T_FINAL                 6
#define CFG_2M_INITIAL                 2
#define CFG_2M_FINAL                   2
#define CFG_PARITY_INITIAL             0
#define CFG_PARITY_FINAL               0
#define CFG_NUM_SP_ANICR               1
#define CFG_ANICR_ONE                  1
#define CFG_ANICR_TWO                  0
#define CFG_ANICR_THREE                0
#define CFG_ANICR_NP                   0
#define CFG_ANICR_IDENT               "n_tables"
#define NP_ORDER                   1
#define CFG_HW                   20.000000
